custom_sched/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('', include('ui.urls', namespace='ui')),
]

this_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('activation_code_api/', include('activation_code_api.urls', namespace='activation_code_api')),
    path('', include('ui.urls', namespace='ui')),
]

ui/urls.py
from django.urls import path
from ui import views

app_name = 'ui'

urlpatterns = [
    path("login", views.LoginView.as_view(), name='login'),
    path("logout", views.LogoutView.as_view(), name='logout'),
    path("password", views.PasswordView.as_view(), name='password'),
    path('codes/', views.ActivationCodesView.as_view(), name="codes"),
    
    path('clear_codes/', views.ClearOldActivationCodesView.as_view(), name="clear_codes"),

    path('sign_up/<str:code>/', views.SignupView.as_view(), name="sign_up"),
    
    path('', views.HomeView.as_view(), name='home'),

]

ui/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from activation_code_api.models import ActivationCode
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.core.management import call_command
from logger import logger
from django.contrib import messages
from activation_code_api.modules.helpers import Helpers
from activation_code_api.exceptions import InvalidCodeException
from activation_code_api.exceptions import ExpiredCodeException
from activation_code_api.exceptions import PasswordDoesNotMatchException
from activation_code_api.exceptions import UserExistsException
from view_classes import SuperUserView

class HomeView(LoginRequiredMixin, View):
    '''
    Home Page View
    '''
    def get(self, request, *args, **kwargs):
        return render(request, 'ui/home.html')

class LoginView(View):
    '''
    Login page view
    '''
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("ui:home")
        return render(request, 'ui/login.html')

    def post(self, request):        
        username = request.POST['u'].lower()
        pwd = request.POST['p']
        user = authenticate(request, username=username, password=pwd)

        if user is not None:
            login(request, user)
            return redirect("ui:home")
        else:
            messages.error(request, 'Login Incorrect')
            return render(request, 'ui/login.html')

class SignupView(View):
    '''
    Signup View (requires access code in URL)
    '''
    def get(self, request, code):
        if request.user.is_authenticated:
            messages.error(request, "You are already logged in.")
            return redirect("ui:home")            
        try:
            valid = Helpers.check_activation_code(code=code)
            assert valid == True
            return render(request, 'ui/signup.html', {'code':code})
        except InvalidCodeException:
            messages.error(request, 'Activation Code Incorrect')
            logger.info(f"Invalid code attempt: {code}")
            return render(request, 'ui/login.html')
        except ExpiredCodeException:
            messages.error(request, 'Activation Code Has Expired')
            logger.info(f"Expired code attempt: {code}")
            return render(request, 'ui/login.html')

    def post(self, request, code):
        code = request.POST['code']
        username = request.POST['username'].lower()
        pwd = request.POST['p1']
        pwd_conf = request.POST['p2']

        try:
            new_user = Helpers.create_new_user_from_activation_code(
                code=code,
                username=username,
                pwd=pwd,
                pwd_conf=pwd_conf,
            )
            login(request, new_user)
            messages.success(request, f"Thank you for signing up, {new_user.username}!")
            return redirect("ui:home")
            return render(request, 'ui/login.html')
        except InvalidCodeException:
            messages.error(request, 'Activation Code Incorrect')
            logger.error(f"Invalid code attempt on POST: {code}")
            return render(request, 'ui/login.html')
        except ExpiredCodeException:
            messages.error(request, 'Activation Code Expired')
            return render(request, 'ui/login.html')
        except UserExistsException:
            messages.error(request, "This user already exists! Either login if you already have an account, or try again with a different username.")
            logger.info(f"User duplicate attempted: {str(username)}")
            return render(request, 'ui/signup.html', {'code':code,  'username':username})
        except PasswordDoesNotMatchException:
            messages.error(request, "Password and password confirmation must match! Please try again")
            return render(request, 'ui/signup.html', {'code':code,  'username':username})
        except Exception as e:
            logger.critical(str(e))
            messages.error(request, "Unable to create account.")
            return render(request, 'ui/signup.html', {'code':code,  'username':username})


class PasswordView(LoginRequiredMixin, View):
    '''
    View to change password
    '''
    def get(self, request):
        return render(request, 'ui/password.html')

    def post(self, request):
        old_pwd = request.POST['p']
        pwd = request.POST['p1']
        pwd_conf = request.POST['p2']

        this_user = authenticate(request, username=request.user.username, password=old_pwd)
        
        if not this_user:
            messages.error(request, "Your old password was incorrect")
            return render(request, 'ui/password.html')

        try:
            Helpers.validate_password(pwd=pwd)
        except Exception as e:
            messages.error(request, f"There was a problem with your password: {str(e)}. Please try again.")
            return render(request, 'ui/password.html')

        try:
            Helpers.compare_passwords(pwd, pwd_conf)
        except PasswordDoesNotMatchException:
            messages.error(request, 'Passwords must match! Please Try again')
            return render(request, 'ui/password.html')

        this_user.set_password(pwd)
        this_user.save()
        
        logout(request)

        new_p_user = authenticate(request, username=this_user.username.lower(), password=pwd)

        if new_p_user is not None:
            login(request, new_p_user)
            messages.success(request, 'Your password has been changed!')
            return redirect("ui:home")
        else:
            messages.error(request, 'Unable to change password. Please login again.')
            return redirect("ui:login")

class LogoutView(LoginRequiredMixin, View):
    '''
    Logout View
    '''
    def get(self, request):
        logout(request)
        return redirect("ui:login")

class ActivationCodesView(SuperUserView):
    '''
    Activation Code view (create/view codes). Requires Superuser
    '''
    def get(self, request):        
        codes = ActivationCode.objects.all().order_by("-expiration_timestamp")
        return render(request, "ui/codes.html", {"codes":codes})
        
    def post(self, request):
        hours = int(request.POST['hours'])
        if hours < 1 or hours > 8760:
            messages.error(request, "Hours must be between 1 and 8760")
            return redirect("ui:codes")
        is_once = True if request.POST.get('once') else False
        call_command('make_code', hours=hours, one_time=is_once)
        messages.success(request,"Code Created!")
        return redirect("ui:codes")

class ClearOldActivationCodesView(SuperUserView):
    '''
    Delete Activation Codes View. Requires Supersuser.
    '''
    def post(self, request):
        call_command("clear_old_codes", confirm=True)
        return redirect("ui:codes")

ui/templates/ui/base.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
    <div class="row">
    <div class="col-sm-9 col-md-8 col-lg-7 mx-auto">
        <div class="card card-signin my-5">
        <div class="card-body">
            <div class='text-center'>
                <h1>AMPETERSON.COM</h1>
                {% if request.user.is_authenticated%}
                    <div>
                        Hi, {{request.user.username}}!
                    </div>
                
                    <div>
                        <a href="{% url 'ui:home' %}">Home</a>
                        |
                        <a href="{% url 'ui:password' %}">Change Password</a>
                        {% if request.user.is_superuser %}
                            |
                            <a href="{% url 'ui:codes' %}">Access Codes</a>
                            |
                            <a href="{% url 'admin:index' %}">Admin</a>
                        {% endif %}
                        |
                        <a href="{% url 'ui:logout' %}">Logout</a>
                {% endif %}
                <br>
                {% block inner_content %}
                <br>
                <br>
                {% endblock %}
                <br>
                
                
            </div>
            <div>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <div style='font-size:1.3em;'>
                            <strong>{{ message }}</strong>
                        </div>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
        </div>
    </div>
    </div>
    </div>
{% endblock %}

ui/templates/ui/codes.html
{% extends 'ui/base.html' %}


{% block inner_content %}
    <div class='text-center'>
        <h5 class="card-title text-center">Create Code</h5>
            <form class="form-signin" action="{% url 'ui:codes' %}", method="POST">
                {% csrf_token %}
                <div class="form-label-group">
                    <input type="number" id="hoursInput" name='hours' class="form-control" value="2" required autofocus>
                    <label min='1' max='8760' for="hours">Hours Before Code Expires</label>
                </div>

                <div>
                    <label for="once">One Time Use?&nbsp;&nbsp;</label><input type="checkbox" id="onceCheckbox" name='once'>
                </div>
                
            <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Create Code</button>
              
        </form>
    </div>
    <hr>
    <h5>Access Codes</h5>
    <table class='table table-striped'>
        <thead>
            <th>Link</th>
            <th>Expiration (UTC)</th>
        <thead>
        <tbody>
            {% for code in codes %}
                <tr>
                    <td>{{code.get_link}}</td>
                    <td>{{code.get_exp_str}}</td>
                </tr>
            {% endfor %}

        </tbody>
    </table>

    
    <form class="form-signin" action="{% url 'ui:clear_codes' %}", method="POST">
        {% csrf_token %}
        <button class="btn btn-lg btn-danger btn-block text-uppercase" type="submit">Delete All Expired Codes</button>
            
    </form>
    <small>To delete other valid codes, please use the <a href="{% url 'admin:index' %}">admin panel</a></small>

    


{% endblock %}

ui/templates/ui/home.html
{% extends 'ui/base.html' %}
{% block inner_content %}
    Here's some stuff:!
{% endblock %}

ui/templates/ui/index.html
{% extends 'ui/base.html' %}
{% block inner_content %}
    Here's some stuff:!
{% endblock %}

ui/templates/ui/login.html
{% extends 'ui/base.html' %}

{% block inner_content %}


        <div class='text-center'>
            <h5 class="card-title text-center">Sign In</h5>
                <form class="form-signin" action="{% url 'ui:login' %}", method="POST">
                {% csrf_token %}

                <div class="form-label-group">
                    <input type="text" id="inputEmail" name='u' class="form-control" placeholder="Username" required autofocus>
                    <label for="inputEmail">Username</label>
                </div>

                <div class="form-label-group">
                    <input type="password" id="inputPassword" name='p' class="form-control" placeholder="Password" required>
                    <label for="inputPassword">Password</label>
                </div>

                

            <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>
              
            </form>
        </div>

{% endblock %}

ui/templates/ui/password.html
{% extends 'ui/base.html' %}

{% block inner_content %}

    <div class='text-center'>
    <h5 class="card-title text-center">Reset Password</h5>
    <form class="form-signin" action="{% url 'ui:password' %}", method="POST">
    {% csrf_token %}

        <div class="form-label-group">
            <input type="password" id="inputPassword" name='p' class="form-control" placeholder="Current Password" required>
            <label for="inputPassword">Current Password</label>
        </div>

        <div class="form-label-group">
            <input type="password" id="inputPassword1" name='p1' class="form-control" placeholder="New Password" required>
            <label for="inputPassword1">New Password</label>
        </div>
        <div class="form-label-group">
            <input type="password" id="inputPassword2" name='p2' class="form-control" placeholder="Repeat Password" required>
            <label for="inputPassword2">Confirm Password</label>
        </div>
        
        <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Reset Password</button>
        
    </form>
        <form class="form-signin" action="{% url 'ui:home' %}", method="GET">
            <button class="btn btn-lg btn-danger btn-block text-uppercase" type="submit">Cancel</button>
        </form>

    </div>
          
{% endblock %}

ui/templates/ui/signup.html
{% extends 'ui/base.html' %}

{% comment %} designed to work with bootstrap 5 {% endcomment %}

{% block inner_content %}

            <h5 class="card-title text-center">Sign Up</h5>
            <small>
              <a href="{% url 'ui:login' %}">Have an account? Login here.</a>
            </small>
            <form class="form-signin" action="{{ code.get_link }}", method="POST">
            {% csrf_token %}
            <input type="hidden" name="code" value="{{code}}">

              <div class="form-label-group">
                <input type="text" id="inputEmail" name='username' class="form-control" placeholder="Username" required autofocus>
                <label for="inputEmail">Username</label>
              </div>

              <div class="form-label-group">
                <input type="password" id="inputPassword" name='p1' class="form-control" placeholder="Password" required>
                <label for="inputPassword">Password</label>
              </div>
              <div class="form-label-group">
                <input type="password" id="inputPassword2" name='p2' class="form-control" placeholder="Password" required>
                <label for="inputPassword2">Confirm Password</label>
              </div>
            <div>
              {{ message }}
              </div>
              

              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>

              
              
            </form>

{% endblock %}